
name: Metrics (examples)
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
jobs:
  github-metrics-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
