
name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics-examples:
    runs-on: ubuntu-latest
    steps:
      - name: 📅 Isocalendar plugin (half year)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
      - name: 🦑 Topics plugin
        uses: lowlighter/metrics@latest
        with:
          filename: topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, js, ts, react, redux, next, express, gatsby, webpack, c++, python, shell, linux, docker, npm, aws, git, 
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_discussions: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics

      - name: 📙 Terminal template
        uses: lowlighter/metrics@latest
        with:
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata
