
name: Terminal
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics-examples:
    runs-on: ubuntu-latest
    steps:
      - name: 📅 Terminal plugin (half year)
        uses: lowlighter/metrics@latest
        with:
          template: terminal
          token: ${{ secrets.METRICS_TOKEN }}
    
